import { Plus, SlidersHorizontal, KeyRound, Power, Pencil } from 'lucide-react';
import { Modal, PageHeading, Pagination } from './ManagementUI';
import React, { useEffect, useState } from 'react';
import { accountApi, AccountPolicy, AccountRecord, Department } from '../api';
import { AuthUser, hasPermission, Permission } from '../lib/permissions';

const labels: Record<string,string>={dashboard_view:'仪表盘',ledger_view:'台账汇总',maintenance_view:'维护与导入页面',ledger_import:'批量导入（可写入基本、销售、采购数据）',data_replace:'替换全部业务数据',department_transfer:'跨部门转移',accounts_view:'账号权限页面',accounts_create:'创建账号',accounts_update:'调整账号权限',accounts_disable:'停用和恢复账号',logs_view:'日志查看',backups_view:'全局备份页面',backups_create:'创建全局备份',backups_verify:'校验备份',backups_restore:'恢复全部业务数据'};
const modules=[['order','基本信息'],['sales','销售信息'],['purchase','采购信息']] as const;
const initial:AccountPolicy={account_type:'department_user',home_department_id:null,scope_mode:'selected',department_ids:[],permissions:[],log_scope:'self'};
const restricted=['accounts_view','accounts_create','accounts_update','accounts_disable','data_replace','backups_restore','department_transfer'];
export default function AccountPermissionsScreen({user}:{user:AuthUser}) {
  const [items,setItems]=useState<AccountRecord[]>([]);const [departments,setDepartments]=useState<Department[]>([]);
  const [page,setPage]=useState(0);const [size,setSize]=useState(5);const [departmentOpen,setDepartmentOpen]=useState(false);
  const [status,setStatus]=useState('active');const [editing,setEditing]=useState<AccountRecord|null|undefined>(undefined);
  const [policy,setPolicy]=useState<AccountPolicy>(initial);const [identity,setIdentity]=useState({username:'',display_name:'',password:''});
  const [reset,setReset]=useState<AccountRecord|null>(null);const [password,setPassword]=useState('');
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [review,setReview]=useState(false);
  const [departmentName,setDepartmentName]=useState('');const [departmentId,setDepartmentId]=useState<number|undefined>();const [departmentActive,setDepartmentActive]=useState(true);
  const superAdmin=user.accountType==='super_admin';const can=(p:string)=>hasPermission(user,p as Permission);
  async function load(){const [a,d]=await Promise.all([accountApi.users(status),accountApi.departments()]);setItems(a.items);setPage(p=>Math.min(p,Math.max(0,Math.ceil(a.items.length/size)-1)));setDepartments(d.items);}
  useEffect(()=>{void load().catch(e=>setMessage(e.message));},[status]);
  async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setMessage('');try{await fn();setMessage('操作成功');await load();}catch(e){setMessage(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
  function open(item:AccountRecord|null){setMessage('');setEditing(item);setReview(false);setPolicy(item?{account_type:item.account_type,home_department_id:item.home_department_id,scope_mode:item.scope_mode,department_ids:item.department_ids,permissions:item.permissions,log_scope:item.log_scope}:{...initial,permissions:[]});setIdentity({username:'',display_name:'',password:''});}
  function toggle(key:string){let permissions=policy.permissions.includes(key)?policy.permissions.filter(p=>p!==key):[...policy.permissions,key];if(['ledger_import','data_replace'].includes(key)&&permissions.includes(key))permissions=[...new Set([...permissions,'maintenance_view'])];if(key.startsWith('accounts_')&&permissions.includes(key))permissions=[...new Set([...permissions,'accounts_view'])];if(key.startsWith('backups_')&&permissions.includes(key))permissions=[...new Set([...permissions,'backups_view'])];setPolicy({...policy,permissions});setReview(false);}
  const scopeText=(p:AccountPolicy)=>p.scope_mode==='all'?'全部门':p.scope_mode==='none'?'无业务数据范围':p.department_ids.map(id=>departments.find(d=>d.id===id)?.name||String(id)).join('、');
  const policyText=(p:AccountPolicy)=>p.account_type==='super_admin'?'全部门；全部权限':`${scopeText(p)}；${p.permissions.map(key=>labels[key]||modules.map(([m,l])=>key.startsWith(m+'_')?l+({view:'查看',entry:'新增',edit:'修改',delete:'删除'}[key.split('_')[1]]||''):null).find(Boolean)||key).join('、')||'无模块权限'}；日志范围：${{self:'本人',department:'部门',all:'全部'}[p.log_scope]}`;
  return <div className="erp-ui space-y-6">
    <PageHeading title="账号与权限" description="管理账号、部门及可访问的数据和功能范围。"/>
    {message&&<p role="status" className="rounded-lg bg-amber-50 p-3 text-sm">{message}</p>}
    <section className="ui-card">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div className="flex items-center gap-5"><h2 className="text-sm font-semibold text-slate-900">账号管理</h2><label className="flex items-center gap-2 text-xs text-slate-500">账号状态<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="active">启用</option><option value="inactive">停用</option></select></label></div>{can('accounts_create')&&<button onClick={()=>open(null)} className="ui-primary"><Plus className="h-4 w-4"/>创建账号</button>}</div>
      <div className="overflow-x-auto"><table className="ui-table"><thead><tr>{['账号 / 显示名称','类型及范围','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.slice(page*size,(page+1)*size).map(item=><tr key={item.id}><td className="min-w-36"><p className="font-medium text-slate-900">{item.username}</p><p className="mt-1 text-slate-500">{item.display_name}</p></td><td className="min-w-60"><p className="font-medium text-slate-800">{{super_admin:'系统超级管理员',ledger_admin:'台账管理员',department_user:'部门账号'}[item.account_type]}</p><p className="mt-1 max-w-lg text-xs leading-5 text-slate-500">{policyText(item)}</p></td><td><div className="flex flex-wrap gap-2 min-w-48">
        {can('accounts_update')&&(superAdmin||item.id!==user.id)&&<button disabled={busy} onClick={()=>open(item)} className="ui-button !text-blue-600"><SlidersHorizontal className="h-3.5 w-3.5"/>配置</button>}
        {can('accounts_disable')&&item.id!==user.id&&<button disabled={busy} className={item.is_active?'ui-danger':'ui-button'} onClick={()=>{if(window.confirm(`确认${item.is_active?'停用':'恢复'}账号 ${item.username}？`))void run(()=>item.is_active?accountApi.disable(item.id):accountApi.restore(item.id));}}><Power className="h-3.5 w-3.5"/>{item.is_active?'停用':'恢复'}</button>}
        {superAdmin&&Boolean(item.is_active)&&<button disabled={busy} className="ui-button" onClick={()=>{setMessage('');setReset(item);setPassword('');}}><KeyRound className="h-3.5 w-3.5"/>重置密码</button>}
      </div></td></tr>)}</tbody></table>{!items.length&&<p className="p-8 text-center text-sm text-slate-500">当前范围内没有账号</p>}</div>
      <Pagination page={page} size={size} total={items.length} onPage={setPage} onSize={setSize}/>
    </section>
    {editing!==undefined&&<Modal wide busy={busy} title={editing?`配置账号 · ${editing.username}`:'创建账号'} onClose={()=>setEditing(undefined)}>{message&&<p role="alert" className="mb-4 rounded-lg bg-amber-50 p-3 text-sm">{message}</p>}
      <form className="space-y-4 text-sm" onSubmit={e=>{e.preventDefault();if(!review){setReview(true);return;}void run(async()=>{if(editing)await accountApi.update(editing.id,policy);else await accountApi.create({...policy,...identity});setEditing(undefined);setReview(false);});}}>
      {!editing&&<div className="grid sm:grid-cols-3 gap-3">{(['username','display_name','password'] as const).map(key=><label key={key} className="text-sm">{{username:'账号（字母、数字、._-）',display_name:'姓名',password:'临时密码（至少12字符）'}[key]}<input className="block border p-2 rounded w-full" required minLength={key==='password'?12:1} maxLength={key==='password'?128:64} type={key==='password'?'password':'text'} autoComplete={key==='password'?'new-password':'off'} value={identity[key]} onChange={e=>{setIdentity({...identity,[key]:e.target.value});setReview(false);}}/></label>)}</div>}
      <div className="flex flex-wrap gap-4"><label>账号类型 <select className="border p-2 rounded" value={policy.account_type} onChange={e=>{const kind=e.target.value as AccountPolicy['account_type'];setPolicy({...policy,account_type:kind,scope_mode:kind==='department_user'?'selected':'all',department_ids:kind==='department_user'&&policy.home_department_id?[policy.home_department_id]:[]});setReview(false);}}><option value="department_user">部门账号</option><option value="ledger_admin">台账管理员</option>{superAdmin&&<option value="super_admin">系统超级管理员</option>}</select></label>
      <label>所属部门 <select className="border p-2 rounded" required={policy.account_type==='department_user'} value={policy.home_department_id||''} onChange={e=>{const id=Number(e.target.value)||null;setPolicy({...policy,home_department_id:id,department_ids:!policy.department_ids.length&&policy.scope_mode==='selected'&&id?[id]:policy.department_ids});setReview(false);}}><option value="">请选择</option>{departments.filter(d=>d.is_active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>
      {policy.account_type==='super_admin'?<p className="bg-amber-50 rounded p-3">超级管理员拥有全部权限。</p>:<>
      <fieldset className="space-y-2"><legend className="font-medium">数据范围</legend>{(['selected','all','none'] as const).filter(mode=>mode!=='all'||superAdmin||user.scopeMode==='all').map(mode=><label key={mode} className="mr-4"><input type="radio" name="scope" checked={policy.scope_mode===mode} onChange={()=>{setPolicy({...policy,scope_mode:mode,department_ids:mode==='selected'&&policy.home_department_id?[policy.home_department_id]:[]});setReview(false);}}/> {{selected:'指定部门',all:'全部门',none:'无业务数据'}[mode]}</label>)}
      {policy.scope_mode==='selected'&&<div>{departments.filter(d=>d.is_active).map(d=><label key={d.id} className="inline-block mr-4"><input type="checkbox" checked={policy.department_ids.includes(d.id)} onChange={()=>{setPolicy({...policy,department_ids:policy.department_ids.includes(d.id)?policy.department_ids.filter(id=>id!==d.id):[...policy.department_ids,d.id]});setReview(false);}}/> {d.name}</label>)}</div>}</fieldset>
      <fieldset className="space-y-3"><legend className="font-medium">业务模块</legend>{modules.map(([module,label])=>{const keys=['view','entry','edit'].map(a=>module+'_'+a);const granted=keys.filter(k=>policy.permissions.includes(k));const level=granted.length===3?'edit':granted.length===1&&granted[0]===keys[0]?'view':granted.length?'custom':'none';return <div key={module} className="flex flex-wrap gap-3 items-center"><span className="w-24">{label}</span><select aria-label={label+"权限"} value={level} className="border p-2 rounded" onChange={e=>{const values=e.target.value==='edit'?keys:e.target.value==='view'?[keys[0]]:[];setPolicy({...policy,permissions:[...policy.permissions.filter(p=>!p.startsWith(module+'_')), ...values]});setReview(false);}}><option value="none">不可访问</option>{can(keys[0])&&<option value="view">仅查看</option>}{keys.every(can)&&<option value="edit">查看及修改</option>}{level==='custom'&&<option value="custom">自定义（保留现有）</option>}</select>{can(module+'_delete')&&<label><input type="checkbox" disabled={level==='none'} checked={policy.permissions.includes(module+'_delete')} onChange={()=>toggle(module+'_delete')}/> 允许删除</label>}</div>;})}</fieldset>
      <fieldset className="grid sm:grid-cols-2 gap-3"><legend className="font-medium mb-2">其他页面与独立操作</legend>{Object.entries(labels).filter(([key])=>can(key)&&(superAdmin||!restricted.includes(key))).map(([key,label])=><label key={key} className="text-sm"><input type="checkbox" checked={policy.permissions.includes(key)} onChange={()=>toggle(key)}/> {label}</label>)}</fieldset>
      <label className="block">日志范围 <select className="border rounded p-2" value={policy.log_scope} onChange={e=>{setPolicy({...policy,log_scope:e.target.value as AccountPolicy['log_scope']});setReview(false);}}><option value="self">本人</option>{(superAdmin||user.logScope!=='self')&&<option value="department">授权部门</option>}{(superAdmin||user.logScope==='all')&&<option value="all">全部</option>}</select></label>
      <p className="text-xs text-slate-500">关闭销售或采购模块不影响已授权台账、仪表盘中的汇总。备份与恢复属于全局操作。日志可能包含业务修改前后内容。</p></>}
      {review&&<div className="bg-blue-50 rounded p-3 text-sm space-y-2">{editing&&<p>修改前：{policyText(editing)}</p>}<p>保存后：{policy.account_type==='super_admin'?'全部权限':policyText(policy)}</p><p>保存后目标账号原有登录会话失效。</p></div>}
      <div className="flex gap-3"><button disabled={busy} className="ui-primary">{busy?'保存中…':review?'确认保存':'检查配置'}</button><button type="button" disabled={busy} className="ui-button" onClick={()=>setEditing(undefined)}>取消</button></div>
      </form></Modal>}
    {reset&&<Modal title={`重置密码 · ${reset.username}`} busy={busy} onClose={()=>setReset(null)}><form className="space-y-4 text-sm" onSubmit={e=>{e.preventDefault();void run(async()=>{await accountApi.reset(reset.id,password);setReset(null);setPassword('');});}}><p className="text-sm text-slate-500">原会话立即失效；用户下次登录须修改临时密码。</p><label className="block text-xs text-slate-500">临时密码<input aria-label="临时密码" className="mt-2 block w-full" type="password" minLength={12} maxLength={128} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p role="alert" className="text-sm text-red-600">{message}</p>}<div className="flex justify-end gap-2"><button type="button" disabled={busy} className="ui-button" onClick={()=>setReset(null)}>取消</button><button disabled={busy} className="ui-primary">确认重置</button></div></form></Modal>}
    {superAdmin&&<section className="ui-card"><div className="flex items-center justify-between gap-4 border-b border-slate-200 p-5"><div><h2 className="text-sm font-semibold text-slate-900">部门管理</h2><p className="mt-1 text-xs text-slate-500">改名保留历史名称；停用后不可用于新业务或新授权。</p></div><button className="ui-primary" onClick={()=>{setMessage('');setDepartmentId(undefined);setDepartmentName('');setDepartmentActive(true);setDepartmentOpen(true);}}><Plus className="h-4 w-4"/>新增部门</button></div><table className="ui-table"><thead><tr><th>部门名称</th><th>状态</th><th>操作</th></tr></thead><tbody>{departments.map(d=><tr key={d.id}><td className="font-medium text-slate-800">{d.name}</td><td><span className={`rounded-full px-2 py-1 text-xs ${d.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{d.is_active?'启用':'停用'}</span></td><td><div className="flex gap-2"><button className="ui-button" onClick={()=>{setMessage('');setDepartmentId(d.id);setDepartmentName(d.name);setDepartmentActive(Boolean(d.is_active));setDepartmentOpen(true);}}><Pencil className="h-3.5 w-3.5"/>修改</button><button disabled={busy} className={d.is_active?'ui-danger':'ui-button'} onClick={()=>{if(window.confirm(`确认${d.is_active?'停用':'启用'}部门“${d.name}”？保存后需要重新登录。`))void run(()=>accountApi.saveDepartment(d.name,!d.is_active,d.id));}}><Power className="h-3.5 w-3.5"/>{d.is_active?'停用':'启用'}</button></div></td></tr>)}</tbody></table></section>}
    {departmentOpen&&<Modal title={departmentId?'修改部门':'新增部门'} busy={busy} onClose={()=>setDepartmentOpen(false)}><form className="space-y-5" onSubmit={e=>{e.preventDefault();void run(async()=>{await accountApi.saveDepartment(departmentName,departmentActive,departmentId);setDepartmentOpen(false);});}}><label className="block text-xs text-slate-500">部门名称<input aria-label="部门名称" required maxLength={64} className="mt-2 block w-full" value={departmentName} onChange={e=>setDepartmentName(e.target.value)}/></label><p className="text-xs text-slate-500">保存部门变更后，账号需要重新登录。</p>{message&&<p role="alert" className="text-sm text-red-600">{message}</p>}<div className="flex justify-end gap-2"><button type="button" disabled={busy} className="ui-button" onClick={()=>setDepartmentOpen(false)}>取消</button><button disabled={busy} className="ui-primary">保存部门</button></div></form></Modal>}
  </div>;
}
