import { Download, Search, RotateCcw, Eye, FileSpreadsheet, CheckCircle, Clock } from 'lucide-react';
import { Modal, PageHeading, Pagination } from './ManagementUI';
import React, { useEffect, useState } from 'react';
import { accountApi, AggregateData, Department, SummaryItem } from '../api';
import { formatMoney } from '../lib/money';
import { AuthUser, hasPermission } from '../lib/permissions';
import { ScreenType } from '../types';

const empty={include_history_manager:'false',project_id:'',order_id:'',department:'',manager:'',client_unit:'',supplier_name:'',start_date:'',end_date:'',invoice_start_date:'',invoice_end_date:'',order_status:''};
export default function SummaryLedgerScreen({user,onNavigate}:{user:AuthUser;onNavigate:(screen:ScreenType)=>void}) {
  const [size,setSize]=useState(5);
  const [selected,setSelected]=useState<SummaryItem|null>(null);
  const [filters,setFilters]=useState(empty);const [applied,setApplied]=useState(empty);const [data,setData]=useState<AggregateData|null>(null);const [departments,setDepartments]=useState<Department[]>([]);const [message,setMessage]=useState('');const [page,setPage]=useState(0);const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;setBusy(true);setSelected(null);setMessage('');accountApi.summary(applied).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setMessage(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[applied]);
  useEffect(()=>{accountApi.departments().then(r=>setDepartments(r.items)).catch(e=>setMessage(e.message));},[]);
  const columns=[['order_value','A销售订单金额'],['purchase_amount','A采购金额'],['delivery_value','B交付收入'],['delivery_cost','B交付成本'],['total_received','D回款金额'],['total_paid','D付款金额'],['sales_invoice_amount','E发票金额'],['total_finance_checked','E收票金额'],['delivery_accounts_receivable','交付应收款'],['invoice_accounts_receivable','开票应收款']] as const;
  const moduleLinks=<div className="flex flex-wrap gap-2">{hasPermission(user,'order_view')&&<button className="ui-button" onClick={()=>onNavigate('orders')}>查看基本信息</button>}{hasPermission(user,'sales_view')&&<button className="ui-button" onClick={()=>onNavigate('sales')}>查看销售信息</button>}{hasPermission(user,'purchase_view')&&<button className="ui-button" onClick={()=>onNavigate('purchases')}>查看采购信息</button>}</div>;
  return <div className="erp-ui space-y-6">
    <PageHeading title="项目台账总览" description="查看项目销售订单、采购金额、回款与应收应付汇总。"><button disabled={busy} className="ui-button" onClick={async()=>{try{const blob=await accountApi.exportSummary(applied);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='台账汇总.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage(e instanceof Error?e.message:'导出失败');}}}><Download className="h-4 w-4 text-blue-600"/>导出台账</button></PageHeading>
    <form className="ui-card p-5 space-y-4" onSubmit={e=>{e.preventDefault();setApplied({...filters});setPage(0);}}>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
        {([['project_id','项目编号'],['order_id','销售订单号'],['manager','客户经理'],['client_unit','客户单位']] as const).map(([key,label])=><label key={key} className="space-y-1.5 text-xs font-medium text-slate-500">{label}<input placeholder={`输入${label}`} className="block w-full mt-1.5" value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}
        <label className="flex items-center gap-2 py-2 text-xs text-slate-500"><input type="checkbox" checked={filters.include_history_manager==='true'} onChange={e=>setFilters({...filters,include_history_manager:String(e.target.checked)})}/>包含历史负责人</label>
        <label className="text-xs font-medium text-slate-500">部门<select className="block w-full mt-1.5" value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})}><option value="">全部部门</option>{departments.filter(d=>d.is_active).map(d=><option key={d.id}>{d.name}</option>)}</select></label>
        <label className="text-xs font-medium text-slate-500">订单状态<select className="block w-full mt-1.5" value={filters.order_status} onChange={e=>setFilters({...filters,order_status:e.target.value})}><option value="">全部</option><option value="open">进行中</option><option value="closed">已关闭</option></select></label>
        <label className="text-xs font-medium text-slate-500">采购厂商<input className="block w-full mt-1.5" placeholder="输入采购厂商名称" value={filters.supplier_name} onChange={e=>setFilters({...filters,supplier_name:e.target.value})}/></label>
        {([['start_date','end_date','销售订单日期'],['invoice_start_date','invoice_end_date','开票日期']] as const).map(([start,end,label])=><fieldset key={start} className="md:col-span-2"><legend className="mb-1.5 text-xs font-medium text-slate-500">{label}</legend><div className="flex items-center gap-2"><input aria-label={label+'开始'} className="w-full min-w-0" type="date" max="2099-12-31" value={filters[start]} onChange={e=>setFilters({...filters,[start]:e.target.value})}/><span className="text-xs text-slate-400">至</span><input aria-label={label+'结束'} className="w-full min-w-0" type="date" max="2099-12-31" value={filters[end]} onChange={e=>setFilters({...filters,[end]:e.target.value})}/></div></fieldset>)}
      </div><div className="flex justify-end gap-2 border-t border-slate-100 pt-3"><button type="button" className="ui-button" onClick={()=>{setFilters(empty);setApplied(empty);setPage(0);}}><RotateCcw className="h-3.5 w-3.5"/>重置</button><button className="ui-primary" disabled={busy}><Search className="h-3.5 w-3.5"/>查询</button></div>
    </form>
    {message&&<p role="alert" className="text-sm text-red-600">{message}</p>}{busy&&<p role="status" className="text-sm text-slate-500">正在加载汇总…</p>}
    {data&&<><section className="ui-card"><div className="overflow-x-auto"><table className="ui-table table-fixed min-w-[2400px]"><thead><tr><th className="w-40">项目编号</th><th className="w-48">客户单位名称</th><th className="w-60">项目名称</th>{columns.map(([key,label])=><th className="w-40 text-right" key={key}>{label}</th>)}<th className="w-28 text-center">操作</th></tr></thead><tbody>{data.items.slice(page*size,(page+1)*size).map(item=><tr key={item.project_code}><td className="font-mono font-medium text-blue-600">{item.project_code}</td><td className="truncate" title={item.customer_unit_name}>{item.customer_unit_name||'-'}</td><td className="truncate" title={item.project_name}><p className="truncate font-medium text-slate-900">{item.project_name||'-'}</p><small className="mt-1 block text-slate-500">现任：{item.account_manager||'-'} · {item.department}</small></td>{columns.map(([key])=><td key={key} className={`text-right font-mono ${key.includes('receivable')?'text-rose-600':''}`}>¥{formatMoney(item[key])}</td>)}<td className="text-center"><button title="查看项目汇总" aria-label={`查看项目 ${item.project_code}`} className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-blue-100 bg-blue-50 text-blue-600 hover:bg-blue-100" onClick={()=>setSelected(item)}><Eye className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!data.items.length&&<p className="p-10 text-center text-sm text-slate-400">没有符合条件的台账记录</p>}</div><Pagination page={page} size={size} total={data.items.length} onPage={setPage} onSize={setSize}/></section>
    <div className="grid sm:grid-cols-3 gap-4">{[{label:'销售订单总额',value:formatMoney(data.metrics.totalOrderAmount)+' 元',icon:FileSpreadsheet,color:'blue'},{label:'已关闭订单',value:data.metrics.closedCount+' 个',icon:CheckCircle,color:'emerald'},{label:'进行中订单',value:(data.metrics.orderCount-data.metrics.closedCount)+' 个',icon:Clock,color:'amber'}].map(({label,value,icon:Icon,color})=><div key={label} className="ui-card flex items-center gap-4 p-5"><div className={`rounded-lg p-3 ${color==='blue'?'bg-blue-50 text-blue-600':color==='emerald'?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}><Icon className="h-5 w-5"/></div><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-bold text-slate-900">{value}</p></div></div>)}</div></>}
    {selected&&<Modal wide title={`${selected.project_code} · 订单经营汇总`} onClose={()=>setSelected(null)}><div className="space-y-5"><p className="text-sm text-slate-500">{selected.project_name}</p><div className="overflow-x-auto rounded-lg border border-slate-200"><table className="ui-table whitespace-nowrap"><thead><tr><th>订单 / 客户</th><th>状态</th>{columns.map(([key,label])=><th key={key} className="text-right">{label}</th>)}</tr></thead><tbody>{selected.orders.map(order=><tr key={order.order_no}><td>{order.order_no}<br/>{order.customer_unit_name}</td><td>{order.status==='closed'?'已关闭':'进行中'}</td>{columns.map(([key])=><td key={key} className="text-right font-mono">¥{formatMoney(order[key])}</td>)}</tr>)}</tbody></table></div>{moduleLinks}</div></Modal>}
  </div>;
}
